inherit_from: .rubocop_todo.yml

AllCops:
  StyleGuideCopsOnly: true

# Uncomment when the violation is fixed
# Metrics/LineLength:
#   Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true
